### ISSUE TITLE
fields and placeholders in results

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#69] opened 2015-06-03 13:46 UTC
In the sidebar and popup results, it would be nice to more clearly see what each item in the result represents. (returned popup fields must be as per #13)

The name of the provider and list of courses are fairly obvious, but 'None' in the popups and the item before the colon in the sidebar results - what do they represent? and if they are empty, do we put dummy or greyed out text in their place?

**Comment by lucernae** [comment] 2015-06-26 11:18
Most of the 'None' popups is caused by incomplete data. I think it is already fixed now. We can close this ticket.

**Closed by lucernae** 2015-06-26 11:18 UTC
