### ISSUE TITLE
Course description

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#38] opened 2015-05-06 22:58 UTC
The course description needs to be shown next to the course and there should be a default showing users that this hasn't yet been loaded.

**Comment by lucernae** [comment] 2015-05-18 09:45
@cchristelis is this a duplicate of #34

**Comment by gubuntu** [comment] 2015-05-26 11:19
no this isn't a duplicate. This refers to course *description*. It should also be expandable on click and not shown by default.

**Closed** 2015-06-01 20:14 UTC
